meta_product_name: "Ágora"
meta_title: "Agora | Publica tus apuntes y empieza a ganar dinero"
meta_description: "Publica tus apuntes y empieza a ganar dinero"
meta_image: "meta-pic.jpeg"                       # El logo va aquí should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
